import { ArrowRight, ArrowUpRight, Camera, Heart, Lightbulb, MessageCircle, Mic, Sparkles } from 'lucide-react';
import type { Screen } from '../../shared/types';
import { ItalianPostcard } from './Illustrations';

export function Home({ navigate, startLive }: { navigate: (screen: Screen) => void; startLive: () => void }) {
  return <main id="main-content" className="home-page">
    <section className="hero"><div className="hero-copy"><div className="destination-tag"><span className="italian-flag" aria-hidden="true" /> JŪSŲ KELIONĖS PALYDOVAS ITALIJOJE</div><h1>Suprasti lengviau.<br /><em>Keliauti drąsiau.</em></h1><p>Kalbėkite lietuviškai. Atraskite Italiją.<br className="desktop-break" /> O visa kita – išversime.</p><div className="hero-note"><Heart size={17} /> Paprasta naudotis. Gera turėti šalia.</div></div><ItalianPostcard /></section>
    <section className="actions-section" aria-labelledby="choose-heading"><div className="section-intro"><h2 id="choose-heading">Kaip galime padėti?</h2><span>Pasirinkite vieną veiksmą</span></div><div className="action-grid">
      <button className="action-card voice-card" onClick={startLive}><span className="card-top"><span className="card-icon"><Mic size={31} strokeWidth={1.7} /></span><span className="card-tag"><span className="mini-dot" /> GYVAI</span></span><span className="card-copy"><span className="card-title">Kalbėtis</span><span className="card-subtitle">Gyvas vertėjas</span><span className="card-description">Jūs kalbate lietuviškai. <br />Pašnekovas girdi itališkai.</span></span><span className="card-bottom"><span>Pradėti pokalbį</span><ArrowUpRight size={26} /></span></button>
      <button className="action-card photo-card" onClick={() => navigate('photo')}><span className="card-top"><span className="card-icon"><Camera size={31} strokeWidth={1.7} /></span><span className="card-decoration" aria-hidden="true">Aa <Sparkles size={13} /></span></span><span className="card-copy"><span className="card-title">Fotografuoti</span><span className="card-subtitle">Išversk, ką matau</span><span className="card-description">Meniu, ženklai ar bilietai – <br />viskas aiškiai lietuviškai.</span></span><span className="card-bottom"><span>Išversti nuotrauką</span><ArrowUpRight size={26} /></span></button>
      <button className="action-card assistant-card" onClick={() => navigate('assistant')}><span className="card-top"><span className="card-icon"><MessageCircle size={31} strokeWidth={1.7} /></span><span className="card-decoration" aria-hidden="true">Ciao!</span></span><span className="card-copy"><span className="card-title">Paklausti</span><span className="card-subtitle">Kelionės asistentas</span><span className="card-description">Klausimai apie Italiją? <br />Atsakysime paprastai.</span></span><span className="card-bottom"><span>Užduoti klausimą</span><ArrowUpRight size={26} /></span></button>
    </div></section>
    <aside className="home-tip"><div className="tip-icon"><Lightbulb size={23} strokeWidth={1.7} /></div><div><strong>Mažas patarimas, lengvesnė kelionė</strong><p>Kalbėdami laikykite telefoną tarp savęs ir pašnekovo. Kalbas atpažinsime patys.</p></div><ArrowRight size={23} className="tip-arrow" aria-hidden="true" /></aside>
    <div className="home-reassurance"><span><span className="little-check">✓</span> Be registracijos</span><span><span className="little-check">✓</span> Lietuviškai</span><span><span className="little-check">✓</span> Visada po ranka</span></div>
  </main>;
}
